service: trabajo-final-jd

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: POST
          path: /hacerPedido

    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: 
          - arn:aws:s3:::order-backup-bucket-trabajo-final-jd/*
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-2:834576715709:order-queue
      - Effect: Allow
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"

  obtenerPedido:
    handler: handler.obtenerPedido
    events:
      - http:
          method: GET
          path: /obtenerPedido

resources:
  Resources:
    Bucketjd:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: order-backup-bucket-trabajo-final-jd
        LifecycleConfiguration:
          Rules:
            - Id: DeleteAfterTwoDays
              Status: Enabled
              ExpirationInDays: 2

    Databasejd:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: restaurantJD
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: MySQL
        EngineVersion: 5.7
        MasterUsername: admin
        MasterUserPassword: 12345678
        MultiAZ: false
        StorageType: gp2
        PubliclyAccessible: true
        VPCSecurityGroups:
          - sg-029a7bbd891969136

    RDSSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: sg-029a7bbd891969136
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

    Queuejd:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: order-queue
        DelaySeconds: 15
        MessageRetentionPeriod: 1036800
